### ISSUE TITLE
Results Component

### ISSUE THREAD

**Issue by fireteam99** [chinese-board-games/luzhanqi-web#38]

**Comment by fireteam99** [comment]
- [ ] Conditionally displays victory or defeat
- [ ] Option to rematch, which moves the state back to lobby
- [ ] Option to quit to menu
- [ ] Basic game stats: how many pieces were taken, time elapsed, etc
- [ ] After a certain time limit, the player is bumped back to the menu

**Comment by iankhou** [comment]
We have victory/defeat and game stats. Removing MVP label.

**Comment by iankhou** [comment]
Option to quit to menu complete. Return home button.
